'use strict';
/* =========================================================================
   Pantry — data layer
   Nutrition values are approximate, per 100 g, from USDA-style references.
   Order: kcal, protein g, carbs g, fat g, fiber g, sodium mg, potassium mg,
          calcium mg, iron mg, vitamin A mcg RAE, vitamin C mg, vitamin D mcg,
          magnesium mg
   ========================================================================= */

const NUT_KEYS = ['kcal','protein','carbs','fat','fiber','sodium','potassium','calcium','iron','vitA','vitC','vitD','magnesium'];

const NUT = {
  beef:        [152,20.9,0,7,0,66,336,12,2.3,0,0,0.1,21],       // 93/7 raw
  chicken:     [120,22.5,0,2.6,0,45,334,5,0.4,9,0,0.1,28],      // breast raw
  p_beef:      [200,27.5,0,9.5,0,85,420,15,3,0,0,0.1,26],       // cooked
  p_chicken:   [165,31,0,3.6,0,74,256,15,1,9,0,0.1,29],         // cooked
  yogurt:      [73,10,3.9,1.9,0,34,141,115,0.1,20,0,0,11],      // 2% Greek
  eggs:        [143,12.6,0.7,9.5,0,142,138,56,1.8,160,0,2,12],
  protein:     [400,78,10,5,1,300,500,450,1,0,0,0,60],          // whey, generic
  rice:        [130,2.7,28.2,0.3,0.4,1,35,10,1.2,0,0,0,12],     // jasmine, cooked, enriched
  p_rice:      [130,2.7,28.2,0.3,0.4,1,35,10,1.2,0,0,0,12],
  ricepouch:   [140,3,30,1,0.5,40,40,10,1,0,0,0,12],
  potatoes:    [77,2,17.5,0.1,2.1,6,425,12,0.8,0,19.7,0,23],
  oats:        [404,14.7,65.7,9.1,6.5,19,371,55,4,0,0,0,144],
  graham:      [430,6.7,77,10.6,2.7,459,135,24,3.3,0,0,0,30],
  bananas:     [89,1.1,22.8,0.3,2.6,1,358,5,0.3,3,8.7,0,27],
  berries:     [45,0.8,11,0.4,2.5,1,120,12,0.4,2,35,0,10],
  broccoli:    [34,2.8,6.6,0.4,2.6,33,316,47,0.7,31,89,0,21],      // raw florets
  corn:        [81,2.6,19,1.2,2.4,1,233,3,0.5,10,5.5,0,26],
  blackbeans:  [91,6,16.6,0.3,6.9,180,300,35,1.9,0,0,0,49],
  lettuce:     [17,1.2,3.3,0.3,2.1,8,247,33,1,436,4,0,14],
  cucumber:    [15,0.7,3.6,0.1,0.5,2,147,16,0.3,5,2.8,0,13],
  tomato:      [18,0.9,3.9,0.2,1.2,5,237,10,0.3,42,13.7,0,11],
  spinach:     [23,2.9,3.6,0.4,2.2,79,558,99,2.7,469,28,0,79],
  peppers:     [30,1,6.5,0.2,1.8,4,200,12,0.4,80,80,0,11],
  greenonion:  [32,1.8,7.3,0.2,2.6,16,276,72,1.5,50,18.8,0,20],
  lemon:       [22,0.4,6.9,0.2,0.3,1,103,6,0.1,1,38.7,0,6],
  lime:        [25,0.4,8.4,0.1,0.4,2,117,14,0.1,2,30,0,8],
  soy:         [53,8.1,4.9,0.6,0.8,3330,217,17,1.5,0,0,0,40],    // low sodium
  bbq:         [172,0.8,40.8,0.6,0.9,1030,232,33,0.9,11,0.6,0,17],
  salsa:       [36,1.5,7,0.2,1.9,430,275,30,0.4,20,4,0,15],
  honey:       [304,0.3,82.4,0,0.2,4,52,6,0.4,0,0.5,0,2],
  maple:       [260,0,67,0.1,0,12,212,102,0.1,0,0,0,21],
  pb:          [588,25,20,50,6,350,649,43,1.9,0,0,0,168],
  oliveoil:    [884,0,0,100,0,2,1,1,0.6,0,0,0,0],
  sesameoil:   [884,0,0,100,0,0,0,0,0,0,0,0,0],
  garlic:      [149,6.4,33,0.5,2.1,17,401,181,1.7,0,31,0,25],
  ginger:      [80,1.8,18,0.8,2,13,415,16,0.6,0,5,0,43],
  cinnamon:    [247,4,81,1.2,53,10,431,1002,8.3,15,3.8,0,60],
  vanilla:     [288,0.1,12.7,0.1,0,9,148,11,0.1,0,0,0,12],
  parmesan:    [392,35.8,3.2,25.8,0,1600,92,1184,0.8,207,0,0.5,44],
  feta:        [264,14.2,4.1,21.3,0,917,62,493,0.7,125,0,0.4,19],
  cumin:       [375,17.8,44,22,10.5,168,1788,931,66,64,7.7,0,366],
  paprika:     [282,14,54,13,35,68,2280,229,21,2463,0.9,0,178],
  smokedpaprika:[282,14,54,13,35,68,2280,229,21,2463,0.9,0,178],
  oregano:     [265,9,69,4.3,42.5,25,1260,1597,37,85,2.3,0,270],
  garlicpowder:[331,16.6,72.7,0.7,9,60,1193,79,5.6,0,1.2,0,77],
  onionpowder: [341,10.4,79,1,15,73,985,384,3.9,0,23,0,122],
  chiliflakes: [318,12,57,17,27,30,2014,148,7.8,2081,0.7,0,152],
  salt:        [0,0,0,0,0,38758,8,24,0.3,0,0,0,1],
  pepper:      [251,10,64,3.3,25,20,1329,443,9.7,27,0,0,171],
  bakingpowder:[53,0,28,0,0.2,10600,20,5876,11,0,0,0,27],
  chips:       [500,5,63,28,7,10,400,40,6,0,0,0,100],
  darkchoc:    [598,7.8,45.9,42.6,10.9,20,715,73,11.9,2,0,0,228],
  cocoa:       [228,19.6,57.9,13.7,37,21,1524,128,13.9,0,0,0,499],
  creamcheese: [350,6.2,5.5,34,0,314,138,97,0.1,308,0,0.4,9],
  milk:        [50,3.3,4.8,2,0,47,140,120,0,55,0,1.2,11],
  butter:      [717,0.9,0.1,81,0,11,24,24,0,684,0,0,2],
  powdered:    [389,0,99.8,0,0,2,2,1,0,0,0,0,0],
  sugar:       [387,0,100,0,0,1,2,1,0,0,0,0,0],
  applesauce:  [42,0.2,11.3,0.1,1.1,2,74,4,0.1,1,1,0,3],
  sesame:      [573,17.7,23.5,49.7,11.8,11,468,975,14.6,0,0,0,351],
  chilisauce:  [93,1.9,19,0.9,2.2,2124,321,18,1.6,0,27,0,16],
  hotsauce:    [12,0.5,0.8,0.4,0.3,2643,144,8,0.5,0,4.5,0,5],
  crispyonion: [600,5,47,43,3,700,200,20,1,0,0,0,20],
  pickles:     [12,0.5,2.3,0.2,1,875,23,44,0.3,0,1,0,4],
  pickledonion:[40,0.5,9,0.1,1,300,100,15,0.2,0,3,0,6],
  cilantro:    [23,2.1,3.7,0.5,2.8,46,521,67,1.8,337,27,0,26],
  jalapeno:    [29,0.9,6.5,0.4,2.8,3,248,12,0.3,54,118,0,15],
  cheese:      [400,23,3,33,0,650,76,700,0.7,260,0,0.6,27],
  olives:      [230,1.5,5,22,3,1500,40,50,1,20,0,0,10],
  hummus:      [166,7.9,14.3,9.6,6,379,228,38,2.4,1,0,0,71],
  herbs:       [36,3,6.3,0.8,3.3,56,554,138,6.2,421,133,0,50],
};

// Label reference values (FDA Daily Values) — used only to give context, not targets.
const DV = { sodium:2300, potassium:4700, calcium:1300, iron:18, vitA:900, vitC:90, vitD:20, magnesium:420 };

/* ---------- Inventory catalog ----------
   shop: how to express a quantity when buying.
     {u:'lb'}                       grams → pounds
     {u:'unit', g, one, many}       grams per purchase unit
     {u:'have'}                     pantry item, no quantity                 */
const CATS = [
  { id:'protein', name:'Protein' },
  { id:'carbs',   name:'Carbs' },
  { id:'produce', name:'Produce' },
  { id:'flavor',  name:'Flavor' },
  { id:'spices',  name:'Spices' },
  { id:'baking',  name:'Baking' },
  { id:'extras',  name:'Toppings & extras' },
  { id:'prepped', name:'Already cooked' },
];

const AISLES = ['Meat','Produce','Dairy & eggs','Frozen','Grains & dry goods','Canned & jarred','Condiments & oils','Spices','Baking','Snacks & toppings','Household'];

const ITEMS = [
  // PROTEIN
  { id:'chicken', name:'Chicken breast', cat:'protein', aisle:'Meat', shop:{u:'lb'} },
  { id:'beef', name:'Lean ground beef (93/7)', cat:'protein', aisle:'Meat', shop:{u:'lb'} },
  { id:'yogurt', name:'Plain Greek yogurt', cat:'protein', aisle:'Dairy & eggs', shop:{u:'unit', g:240, one:'cup', many:'cups', hint:'32-oz tub ≈ 3½ cups'} },
  { id:'eggs', name:'Eggs', cat:'protein', aisle:'Dairy & eggs', shop:{u:'unit', g:50, one:'egg', many:'eggs', round:1} },
  { id:'protein', name:'Protein powder', cat:'protein', aisle:'Baking', shop:{u:'unit', g:30, one:'scoop', many:'scoops', round:1} },
  // CARBS
  { id:'rice', name:'Jasmine rice', cat:'carbs', aisle:'Grains & dry goods', shop:{u:'unit', g:474, one:'cup dry', many:'cups dry', round:0.5} },
  { id:'ricepouch', name:'Microwave rice pouches', cat:'carbs', aisle:'Grains & dry goods', shop:{u:'unit', g:250, one:'pouch', many:'pouches', round:1} },
  { id:'potatoes', name:'Potatoes (Yukon Gold)', cat:'carbs', aisle:'Produce', shop:{u:'lb'} },
  { id:'oats', name:'Oats / oat flour', cat:'carbs', alsoCat:'baking', aisle:'Grains & dry goods', shop:{u:'unit', g:90, one:'cup', many:'cups', round:0.5} },
  { id:'graham', name:'Graham crackers', cat:'carbs', aisle:'Snacks & toppings', shop:{u:'have'} },
  // PRODUCE
  { id:'bananas', name:'Bananas', cat:'produce', aisle:'Produce', shop:{u:'unit', g:118, one:'banana', many:'bananas', round:1} },
  { id:'berries', name:'Berries', cat:'produce', aisle:'Produce', shop:{u:'unit', g:150, one:'cup', many:'cups', round:0.5} },
  { id:'broccoli', name:'Broccoli florets', cat:'produce', aisle:'Produce', shop:{u:'lb'} },
  { id:'corn', name:'Corn (frozen)', cat:'produce', aisle:'Frozen', shop:{u:'unit', g:165, one:'cup', many:'cups', round:0.5, hint:'12-oz bag ≈ 2 cups'} },
  { id:'blackbeans', name:'Black beans', cat:'produce', aisle:'Canned & jarred', shop:{u:'unit', g:255, one:'can (15 oz)', many:'cans (15 oz)', round:1} },
  { id:'lettuce', name:'Romaine lettuce', cat:'produce', aisle:'Produce', shop:{u:'unit', g:280, one:'head', many:'heads', round:1} },
  { id:'cucumber', name:'Cucumber', cat:'produce', aisle:'Produce', shop:{u:'unit', g:300, one:'cucumber', many:'cucumbers', round:1} },
  { id:'tomato', name:'Cherry tomatoes', cat:'produce', aisle:'Produce', shop:{u:'unit', g:300, one:'pint', many:'pints', round:1} },
  { id:'spinach', name:'Baby spinach', cat:'produce', aisle:'Produce', shop:{u:'unit', g:142, one:'box (5 oz)', many:'boxes (5 oz)', round:1} },
  { id:'peppers', name:'Peppers & onions', cat:'produce', aisle:'Produce', shop:{u:'lb'} },
  { id:'greenonion', name:'Green onions', cat:'produce', aisle:'Produce', shop:{u:'unit', g:100, one:'bunch', many:'bunches', round:1} },
  { id:'lemon', name:'Lemons', cat:'produce', aisle:'Produce', shop:{u:'unit', g:45, one:'lemon', many:'lemons', round:1} },
  { id:'lime', name:'Limes', cat:'produce', aisle:'Produce', shop:{u:'unit', g:30, one:'lime', many:'limes', round:1} },
  // FLAVOR
  { id:'soy', name:'Low-sodium soy sauce', cat:'flavor', aisle:'Condiments & oils', shop:{u:'have'} },
  { id:'bbq', name:'BBQ sauce', cat:'flavor', aisle:'Condiments & oils', shop:{u:'have'} },
  { id:'salsa', name:'Salsa', cat:'flavor', aisle:'Canned & jarred', shop:{u:'unit', g:450, one:'jar (16 oz)', many:'jars (16 oz)', round:1} },
  { id:'honey', name:'Honey', cat:'flavor', aisle:'Condiments & oils', shop:{u:'have'} },
  { id:'maple', name:'Maple syrup', cat:'flavor', aisle:'Condiments & oils', shop:{u:'have'} },
  { id:'pb', name:'Peanut butter', cat:'flavor', aisle:'Condiments & oils', shop:{u:'have'} },
  { id:'oliveoil', name:'Olive oil', cat:'flavor', aisle:'Condiments & oils', shop:{u:'have'}, staple:true },
  { id:'sesameoil', name:'Sesame oil', cat:'flavor', aisle:'Condiments & oils', shop:{u:'have'} },
  { id:'garlic', name:'Garlic', cat:'flavor', aisle:'Produce', shop:{u:'unit', g:30, one:'head', many:'heads', round:1} },
  { id:'ginger', name:'Fresh ginger', cat:'flavor', aisle:'Produce', shop:{u:'unit', g:6, one:'1-inch piece', many:'1-inch pieces', round:1} },
  { id:'cinnamon', name:'Cinnamon', cat:'flavor', aisle:'Spices', shop:{u:'have'} },
  { id:'vanilla', name:'Vanilla extract', cat:'flavor', aisle:'Baking', shop:{u:'have'} },
  { id:'parmesan', name:'Parmesan', cat:'flavor', aisle:'Dairy & eggs', shop:{u:'have'} },
  { id:'feta', name:'Feta', cat:'flavor', aisle:'Dairy & eggs', shop:{u:'unit', g:28, one:'oz', many:'oz', round:1} },
  // SPICES
  { id:'cumin', name:'Cumin', cat:'spices', aisle:'Spices', shop:{u:'have'}, staple:true },
  { id:'paprika', name:'Paprika', cat:'spices', aisle:'Spices', shop:{u:'have'}, staple:true },
  { id:'smokedpaprika', name:'Smoked paprika', cat:'spices', aisle:'Spices', shop:{u:'have'}, staple:true },
  { id:'oregano', name:'Dried oregano', cat:'spices', aisle:'Spices', shop:{u:'have'}, staple:true },
  { id:'garlicpowder', name:'Garlic powder', cat:'spices', aisle:'Spices', shop:{u:'have'}, staple:true },
  { id:'onionpowder', name:'Onion powder', cat:'spices', aisle:'Spices', shop:{u:'have'}, staple:true },
  { id:'chiliflakes', name:'Red pepper flakes', cat:'spices', aisle:'Spices', shop:{u:'have'} },
  { id:'salt', name:'Salt', cat:'spices', aisle:'Spices', shop:{u:'have'}, staple:true },
  { id:'pepper', name:'Black pepper', cat:'spices', aisle:'Spices', shop:{u:'have'}, staple:true },
  // BAKING
  { id:'bakingpowder', name:'Baking powder', cat:'baking', aisle:'Baking', shop:{u:'have'} },
  { id:'chips', name:'Dark chocolate chips', cat:'baking', aisle:'Baking', shop:{u:'unit', g:170, one:'cup', many:'cups', round:0.5, hint:'10-oz bag ≈ 1⅔ cups'} },
  { id:'darkchoc', name:'Dark chocolate bar (70%)', cat:'baking', aisle:'Baking', shop:{u:'unit', g:28.35, one:'oz', many:'oz', round:1} },
  { id:'cocoa', name:'Unsweetened cocoa', cat:'baking', aisle:'Baking', shop:{u:'have'} },
  { id:'creamcheese', name:'Cream cheese', cat:'baking', aisle:'Dairy & eggs', shop:{u:'have'} },
  { id:'milk', name:'Milk', cat:'baking', aisle:'Dairy & eggs', shop:{u:'unit', g:244, one:'cup', many:'cups', round:0.5} },
  { id:'butter', name:'Butter', cat:'baking', aisle:'Dairy & eggs', shop:{u:'have'} },
  { id:'powdered', name:'Powdered sugar', cat:'baking', aisle:'Baking', shop:{u:'have'} },
  { id:'sugar', name:'Sugar', cat:'baking', aisle:'Baking', shop:{u:'have'} },
  { id:'applesauce', name:'Unsweetened applesauce', cat:'baking', aisle:'Canned & jarred', shop:{u:'have'} },
  { id:'parchment', name:'Parchment paper', cat:'baking', aisle:'Household', shop:{u:'have'} },
  // EXTRAS
  { id:'sesame', name:'Sesame seeds', cat:'extras', aisle:'Spices', shop:{u:'have'} },
  { id:'chilisauce', name:'Gochujang or sriracha', cat:'extras', aisle:'Condiments & oils', shop:{u:'have'} },
  { id:'hotsauce', name:'Hot sauce', cat:'extras', aisle:'Condiments & oils', shop:{u:'have'} },
  { id:'crispyonion', name:'Crispy fried onions', cat:'extras', aisle:'Snacks & toppings', shop:{u:'have'} },
  { id:'pickles', name:'Dill pickles', cat:'extras', aisle:'Canned & jarred', shop:{u:'have'} },
  { id:'pickledonion', name:'Pickled red onions', cat:'extras', aisle:'Canned & jarred', shop:{u:'have'} },
  { id:'cilantro', name:'Cilantro', cat:'extras', aisle:'Produce', shop:{u:'unit', g:60, one:'bunch', many:'bunches', round:1} },
  { id:'jalapeno', name:'Jalapeño', cat:'extras', aisle:'Produce', shop:{u:'unit', g:14, one:'pepper', many:'peppers', round:1} },
  { id:'cheese', name:'Shredded cheese', cat:'extras', aisle:'Dairy & eggs', shop:{u:'have'} },
  { id:'olives', name:'Kalamata olives', cat:'extras', aisle:'Canned & jarred', shop:{u:'have'} },
  { id:'hummus', name:'Hummus', cat:'extras', aisle:'Dairy & eggs', shop:{u:'have'} },
  { id:'herbs', name:'Fresh dill or parsley', cat:'extras', aisle:'Produce', shop:{u:'unit', g:30, one:'bunch', many:'bunches', round:1} },
  // PREPPED (set by Prep mode)
  { id:'p_rice', name:'Cooked rice', cat:'prepped', aisle:'Grains & dry goods', shop:{u:'have'}, prepped:true },
  { id:'p_chicken', name:'Cooked chicken', cat:'prepped', aisle:'Meat', shop:{u:'have'}, prepped:true },
  { id:'p_beef', name:'Cooked ground beef', cat:'prepped', aisle:'Meat', shop:{u:'have'}, prepped:true },
];
const ITEM = Object.fromEntries(ITEMS.map(i => [i.id, i]));

/* ---------- Shared step fragments ---------- */
const RICE_STEP = {
  if:'fresh', key:'rice', title:'Start the rice', hands:3, passive:17, timer:12,
  text:'Rinse {dry} jasmine rice in a strainer until the water runs mostly clear. Put it in a small pot with {water} water and a pinch of salt. Bring to a boil, cover, turn the heat to low and cook 12 minutes. Turn off the heat and leave the lid on — it keeps steaming.',
  tip:'Rice cooker instead: jasmine or white setting, water to the line for {dry} rice. It can take 25–30 minutes, so start it first.',
  timerNote:'Start the timer once the water boils and the lid goes on.',
};
const WARM_RICE_STEP = {
  if:'ready', title:'Warm the rice', hands:2,
  text:'Microwave {q:rice} cooked rice covered with a damp paper towel for 1½–2 minutes, until steaming. Using a pouch? Follow the package — usually 90 seconds.',
};
const CHICKEN_SAFETY = 'Chicken is safe at 165°F in the thickest piece: no pink inside, juices run clear.';
const BEEF_SAFETY = 'Ground beef is safe at 160°F: no pink left.';

/* ---------- Dinners ---------- */
const RECIPES = [
{
  id:'korean', type:'dinner', name:'Korean Beef Bowl', short:'Korean Beef',
  flavor:'Sweet-savory beef glazed with soy, honey, garlic and ginger, over jasmine rice with broccoli.',
  difficulty:'Easy', protein:'beef', tags:['beef','one pan','freezes well'],
  bowl:[['rice',0.42],['beef',0.34],['broccoli',0.24]], garnish:'greenonion',
  ingredients:[
    { id:'beef', q:10, u:'oz', g:283, role:'protein', core:true, any:['beef','p_beef'], note:'raw · about 8 oz cooked', sub:'Ground turkey works — add ¼ tsp extra sesame oil.' },
    { id:'rice', name:'Jasmine rice', q:1.5, u:'cup', g:237, role:'carb', core:true, any:['rice','p_rice','ricepouch'], note:'cooked · {dry} dry' },
    { id:'broccoli', q:1.5, u:'cup', g:135, role:'veg', core:true, note:'fresh or frozen florets', sub:'Frozen florets are the fastest option.' },
    { id:'greenonion', q:2, u:'tbsp', g:12, role:'garnish', note:'sliced', sub:'Skip it, or use chives.' },
    { id:'soy', q:1.25, u:'tbsp', g:20, role:'sauce', core:true, group:'Sauce' },
    { id:'honey', q:2, u:'tsp', g:14, role:'sauce', group:'Sauce', any:['honey','maple'], sub:'Maple syrup or brown sugar.' },
    { id:'sesameoil', q:0.5, u:'tsp', g:2.3, role:'sauce', group:'Sauce', sub:'Leave it out — the sauce is less nutty but still good.' },
    { id:'garlic', q:1, u:'clove', g:3, role:'aromatic', group:'Sauce', any:['garlic','garlicpowder'], sub:'¼ tsp garlic powder, stirred into the sauce.' },
    { id:'ginger', q:1, u:'tsp', g:2, role:'aromatic', group:'Sauce', sub:'⅛ tsp ground ginger, stirred into the sauce.' },
  ],
  heat:{
    medium:[{ id:'chilisauce', q:1, u:'tsp', g:6, note:'stirred into the sauce' }],
    hot:[{ id:'chilisauce', q:2, u:'tsp', g:12, note:'stirred into the sauce' }],
  },
  heatText:' Stir in {q:chilisauce} gochujang or sriracha.',
  tiers:{
    base:{ text:'Beef, rice, broccoli, sauce, green onion.' },
    better:{ text:'Toasted sesame seeds, a squeeze of lime, extra green onion.', finish:'Sprinkle sesame seeds and extra green onion, then squeeze a lime wedge over the bowl.',
      add:[{ id:'sesame', q:1, u:'tsp', g:3 },{ id:'lime', q:1, u:'wedge', g:5 },{ id:'greenonion', key:'greenonion2', q:1, u:'tbsp', g:6, note:'extra' }] },
    loaded:{ text:'Everything in Better, plus crispy onions and a thin drizzle of chili sauce.', finish:'Add a handful of crispy onions and a thin line of chili sauce.',
      add:[{ id:'crispyonion', q:2, u:'tbsp', g:7 },{ id:'chilisauce', key:'chiliTop', q:0.5, u:'tsp', g:3, note:'small drizzle' }] },
  },
  equipment:['Large skillet (12-inch)','Small pot with lid, or a rice cooker','Microwave-safe bowl and a plate to cover it','Small bowl for the sauce','Spatula'],
  mise:['Beef from the fridge','Rice and a measuring cup','Broccoli','Soy sauce, honey, sesame oil','Garlic, ginger and a grater','Green onion','Your bowl'],
  steps:[
    RICE_STEP,
    { title:'Mix the sauce', prep:true, hands:3,
      text:'In a small bowl, stir {q:soy} soy sauce, {q:honey} honey and {q:sesameoil} sesame oil.{heat} Mince {q:garlic} garlic and grate {q:ginger} ginger — keep those separate. They go into the pan first.' },
    { key:'beef', title:'Brown the beef', hands:1, passive:7, timer:7,
      text:'Heat the skillet over medium-high for 1 minute. Add {q:beef} beef and press it into one flat layer. Leave it for 2 minutes to brown, then break it into crumbles and cook until no pink remains, 6–8 minutes total.',
      warn:'Don’t stir right away. The browned crust is where the flavor comes from.', safety:BEEF_SAFETY },
    { key:'veg', title:'Cook the broccoli', hands:1, passive:4, timer:4,
      text:'While the beef browns: put {q:broccoli} broccoli in a microwave-safe bowl with 2 tbsp water. Cover with a plate and microwave 3–4 minutes (frozen: 4–5), until bright green and just tender.' },
    { waitFor:'beef', title:'Drain, then garlic and ginger', hands:1,
      text:'If fat has pooled, tilt the pan and spoon it off — lean beef often has very little. Push the beef aside, add the garlic and ginger to the bare spot and stir for 30 seconds until fragrant, then mix everything together.',
      warn:'30 seconds is enough. Garlic turns bitter once it browns.' },
    { key:'sauce', title:'Add the sauce', hands:1, passive:2, timer:2,
      text:'Pour in the sauce and stir. Simmer 2 minutes, until glossy and mostly clinging to the beef.' },
    { title:'Slice the green onion', prep:true, hands:1,
      text:'Thinly slice {q:greenonion} green onion. Drain the broccoli.' },
    WARM_RICE_STEP,
    { waitAll:true, title:'Assemble', hands:2,
      text:'Rice on the bottom. Beef on one side, broccoli on the other. Spoon any sauce left in the pan over the broccoli.' },
    { title:'Finish', hands:1, finish:true,
      text:'Green onion on top.{tierFinish} Taste the beef — a few drops of soy if it needs more salt.' },
  ],
  finish:'Rice on the bottom, beef on one side, broccoli on the other. Spoon the pan sauce over the broccoli so nothing is plain. Green onion on top.',
  subs:['No fresh ginger: ⅛ tsp ground ginger in the sauce.','No honey: maple syrup, or 2 tsp brown sugar.','Potatoes instead of rice: use the potato method from the BBQ bowl.'],
  leftovers:{
    separate:['Beef, rice and broccoli can share one container.','No separate sauce needed — the beef is already glazed.','Keep green onion, sesame seeds, lime and crispy onions out. They go on after reheating.'],
    storage:['Get it cold fast: shallow containers, into the fridge within 2 hours of cooking — within 1 hour for the rice if you can.','Fridge: eat within 3–4 days.','Freezer: up to 2–3 months for best quality. Broccoli goes soft after freezing, so freeze beef and rice, and add fresh broccoli later if you can.','Thaw overnight in the fridge, not on the counter.'],
    reheat:['Sprinkle 1 tbsp water over the rice and cover loosely.','Microwave 1½ minutes, stir, then 1–1½ minutes more, until steaming hot all the way through (165°F).','From frozen: 50% power for 3–4 minutes, stir, then full power until hot.','Reheat a portion once. Don’t cool it and reheat it again.'],
    fresh:['Fresh green onion and a squeeze of lime.','A ½-tsp splash of soy mixed with a little honey to wake up the glaze.'],
  },
},
{
  id:'mexican', type:'dinner', name:'Mexican Chicken Bowl', short:'Mexican Chicken',
  flavor:'Cumin-paprika chicken with lime, black beans, corn and a cool salsa-yogurt sauce. Mild by default.',
  difficulty:'Easy', protein:'chicken', tags:['chicken','mild','no avocado'],
  bowl:[['rice',0.34],['chicken',0.30],['lettuce',0.14],['beans',0.11],['corn',0.11]], garnish:'salsa',
  ingredients:[
    { id:'chicken', q:11, u:'oz', g:312, role:'protein', core:true, any:['chicken','p_chicken'], note:'raw breast · about 8 oz cooked', sub:'Boneless thighs stay juicier and reheat better. Same method; cook to 175°F.' },
    { id:'rice', name:'Jasmine rice', q:1.5, u:'cup', g:237, role:'carb', core:true, any:['rice','p_rice','ricepouch'], note:'cooked · {dry} dry' },
    { id:'blackbeans', q:0.333, u:'cup', g:57, role:'veg', note:'rinsed' },
    { id:'corn', q:0.333, u:'cup', g:55, role:'veg', note:'frozen is fine' },
    { id:'lettuce', q:1, u:'cup', g:47, role:'veg', any:['lettuce','peppers','spinach'], note:'shredded', sub:'Fajita vegetables instead: sauté 1 cup sliced peppers and onions in the pan after the chicken.' },
    { id:'salsa', q:2, u:'tbsp', g:32, role:'sauce', core:true, group:'Sauce', note:'half on top, half in the sauce' },
    { id:'yogurt', q:2, u:'tbsp', g:30, role:'sauce', group:'Sauce' },
    { id:'lime', q:0.5, u:'lime', g:15, role:'sauce', group:'Sauce', any:['lime','lemon'], note:'juiced', sub:'Lemon juice.' },
    { id:'oliveoil', q:1, u:'tsp', g:4.5, role:'other', group:'Chicken seasoning' },
    { id:'cumin', q:0.5, u:'tsp', g:1, role:'other', group:'Chicken seasoning' },
    { id:'garlicpowder', q:0.5, u:'tsp', g:1.5, role:'other', group:'Chicken seasoning' },
    { id:'onionpowder', q:0.25, u:'tsp', g:0.6, role:'other', group:'Chicken seasoning' },
    { id:'paprika', q:0.5, u:'tsp', g:1.2, role:'other', group:'Chicken seasoning' },
    { id:'salt', q:0.25, u:'tsp', g:1.5, role:'other', group:'Chicken seasoning' },
    { id:'pepper', q:0.125, u:'tsp', g:0.3, role:'other', group:'Chicken seasoning' },
  ],
  heat:{
    medium:[{ id:'jalapeno', q:1, u:'tbsp', g:6, note:'diced, seeds removed' }],
    hot:[{ id:'jalapeno', q:1, u:'tbsp', g:6, note:'diced, seeds in' },{ id:'hotsauce', q:1, u:'tsp', g:5, note:'on top at the end' }],
  },
  heatText:{ medium:' Dice {q:jalapeno} jalapeño, seeds removed.', hot:' Dice {q:jalapeno} jalapeño with the seeds; {q:hotsauce} hot sauce goes on at the end.' },
  tiers:{
    base:{ text:'Chicken, rice, beans, corn, lettuce, salsa, salsa-yogurt sauce.' },
    better:{ text:'Pickled onions, cilantro and an extra spoon of salsa.', finish:'Add pickled onions, cilantro and the extra salsa.',
      add:[{ id:'pickledonion', q:2, u:'tbsp', g:20 },{ id:'cilantro', q:1, u:'tbsp', g:1, note:'chopped' },{ id:'salsa', key:'salsa2', q:1, u:'tbsp', g:16, note:'extra' }] },
    loaded:{ text:'Everything in Better, plus melted cheese and charred fajita vegetables.', finish:'Scatter the cheese over the hot chicken so it melts, and pile on the fajita vegetables.',
      add:[{ id:'cheese', q:0.25, u:'cup', g:28 },{ id:'peppers', q:1, u:'cup', g:110, note:'sliced, sautéed' }] },
  },
  equipment:['Large skillet (12-inch)','Small pot with lid, or a rice cooker','Cutting board and knife','Two small bowls','Microwave-safe bowl','Instant-read thermometer (recommended)'],
  mise:['Chicken from the fridge','Rice','Black beans and a can opener','Corn','Lettuce','Salsa, Greek yogurt, lime','Olive oil and the six seasonings'],
  steps:[
    RICE_STEP,
    { title:'Season the chicken', prep:true, hands:5,
      text:'Cut {q:chicken} chicken into 1-inch pieces and pat dry. In a bowl, toss with {q:oliveoil} olive oil, {q:cumin} cumin, {q:garlicpowder} garlic powder, {q:onionpowder} onion powder, {q:paprika} paprika, {q:salt} salt, a pinch of pepper and half the lime juice.',
      warn:'Wash your hands, knife and board after handling raw chicken.' },
    { key:'chicken', title:'Sear the chicken', hands:1, passive:9, timer:9,
      text:'Heat the skillet over medium-high for 2 minutes. Add the chicken in a single layer. Leave it for 3 minutes to brown, then stir every couple of minutes until cooked through, 8–10 minutes total.',
      safety:CHICKEN_SAFETY },
    { key:'beans', title:'Warm the beans and corn', hands:1, passive:2, timer:2,
      text:'While the chicken cooks: rinse {q:blackbeans} black beans. Microwave them with {q:corn} corn in a covered bowl for 2 minutes, stir, and add a pinch of salt.' },
    { title:'Mix the salsa-yogurt sauce', prep:true, hands:2,
      text:'Stir {q:yogurt} Greek yogurt with half the salsa, the rest of the lime juice and a pinch of salt. Thin with a teaspoon of water if you want to drizzle it.' },
    { title:'Prep the lettuce', prep:true, hands:2,
      text:'Shred {q:lettuce} romaine.{heat}' },
    { waitFor:'chicken', title:'Check the chicken', hands:1,
      text:'Cut open the thickest piece: no pink inside. Take the pan off the heat and let it rest for 2 minutes.', safety:CHICKEN_SAFETY },
    { if:'loaded', key:'fajita', title:'Char the fajita vegetables', hands:1, passive:5, timer:5,
      text:'Move the chicken to a plate. Add {q:peppers} sliced peppers and onions to the hot pan with a pinch of salt. Cook 4–5 minutes, until charred at the edges.' },
    WARM_RICE_STEP,
    { waitAll:true, title:'Assemble', hands:2,
      text:'Rice first, then lettuce, beans and corn, then the chicken. Spoon the remaining salsa over the chicken and the yogurt sauce over everything.' },
    { title:'Finish', hands:1, finish:true,
      text:'Taste a bite with sauce — a pinch of salt or a little more lime if it needs it.{tierFinish}' },
  ],
  finish:'Rice, then lettuce, beans and corn, then chicken. Salsa on the chicken, salsa-yogurt sauce over the whole bowl.',
  subs:['Thighs instead of breast: juicier, forgiving on reheat. Cook to 175°F.','No lime: lemon juice.','Want heat? Change Heat to medium or hot in Settings — the default stays mild.'],
  leftovers:{
    separate:['Chicken, rice, beans and corn go in one container.','Lettuce, salsa and the salsa-yogurt sauce each go in their own small container. Never microwave them.','Cheese, cilantro and pickled onions go on after reheating.'],
    storage:['Into the fridge within 2 hours of cooking — within 1 hour for rice if you can.','Cooked chicken and rice: 3–4 days in the fridge.','Salsa-yogurt sauce: 3–4 days, kept cold. Stir before using.','Shredded lettuce: 2–3 days with a paper towel in the container.','Freezer: chicken, rice, beans and corn for up to 2–3 months. Don’t freeze the sauce or lettuce.'],
    reheat:['Sprinkle 1 tbsp water over the rice and chicken and cover loosely.','Microwave 1½ minutes. Stir, move chicken from the edges to the center, then 1–1½ minutes more until steaming throughout (165°F).','Stop as soon as it’s hot. Extra minutes are what dry chicken out.','Add the cold lettuce, salsa and sauce after heating.'],
    fresh:['A fresh squeeze of lime and a spoon of cold salsa.','A little cheese right after heating so it melts.'],
  },
},
{
  id:'med', type:'dinner', name:'Mediterranean Chicken Bowl', short:'Mediterranean Chicken',
  flavor:'Lemon-oregano chicken with cucumber, tomato and spinach, finished with a garlic yogurt sauce.',
  difficulty:'Easy', protein:'chicken', tags:['chicken','fresh','bright'],
  bowl:[['rice',0.34],['chicken',0.30],['spinach',0.12],['cucumber',0.12],['tomato',0.12]], garnish:'yogurt',
  ingredients:[
    { id:'chicken', q:11, u:'oz', g:312, role:'protein', core:true, any:['chicken','p_chicken'], note:'raw breast · about 8 oz cooked', sub:'Boneless thighs stay juicier. Cook to 175°F.' },
    { id:'rice', name:'Jasmine rice', q:1.5, u:'cup', g:237, role:'carb', core:true, any:['rice','p_rice','ricepouch'], note:'cooked · {dry} dry' },
    { id:'cucumber', q:0.5, u:'cup', g:70, role:'veg', core:true, note:'diced' },
    { id:'tomato', q:0.5, u:'cup', g:90, role:'veg', note:'cherry tomatoes, halved' },
    { id:'spinach', q:1, u:'cup', g:30, role:'veg', any:['spinach','lettuce'], note:'baby spinach', sub:'Romaine works.' },
    { id:'oliveoil', q:2, u:'tsp', g:9, role:'other', group:'Chicken seasoning' },
    { id:'garlic', q:1, u:'clove', g:3, role:'aromatic', group:'Chicken seasoning', any:['garlic','garlicpowder'], note:'minced', sub:'¼ tsp garlic powder.' },
    { id:'oregano', q:1, u:'tsp', g:1, role:'other', group:'Chicken seasoning' },
    { id:'paprika', q:0.5, u:'tsp', g:1.2, role:'other', group:'Chicken seasoning' },
    { id:'lemon', q:1, u:'tbsp', g:15, role:'other', group:'Chicken seasoning', note:'juice', any:['lemon','lime'] },
    { id:'salt', q:0.25, u:'tsp', g:1.5, role:'other', group:'Chicken seasoning' },
    { id:'pepper', q:0.125, u:'tsp', g:0.3, role:'other', group:'Chicken seasoning' },
    { id:'yogurt', q:2, u:'tbsp', g:30, role:'sauce', core:true, group:'Garlic yogurt sauce' },
    { id:'lemon', key:'lemonSauce', q:1, u:'tsp', g:5, role:'sauce', group:'Garlic yogurt sauce', note:'juice', any:['lemon','lime'] },
    { id:'garlic', key:'garlicSauce', q:0.5, u:'clove', g:1.5, role:'sauce', group:'Garlic yogurt sauce', any:['garlic','garlicpowder'], note:'grated' },
  ],
  heat:{
    medium:[{ id:'chiliflakes', q:0.25, u:'tsp', g:0.5 }],
    hot:[{ id:'chiliflakes', q:0.5, u:'tsp', g:1 }],
  },
  heatText:' Sprinkle {q:chiliflakes} red pepper flakes over the vegetables.',
  tiers:{
    base:{ text:'Chicken, rice, cucumber, tomato, spinach, garlic yogurt sauce.' },
    better:{ text:'Crumbled feta, fresh dill or parsley, an extra lemon wedge.', finish:'Crumble the feta over, add the herbs and squeeze the lemon wedge.',
      add:[{ id:'feta', q:1, u:'oz', g:28 },{ id:'herbs', q:1, u:'tbsp', g:4, note:'chopped' },{ id:'lemon', key:'lemonWedge', q:1, u:'wedge', g:8 }] },
    loaded:{ text:'Everything in Better, plus kalamata olives, hummus and pickled onions.', finish:'Add the olives, a spoon of hummus on the side and the pickled onions.',
      add:[{ id:'olives', q:5, u:'olive', g:20 },{ id:'hummus', q:2, u:'tbsp', g:30 },{ id:'pickledonion', q:2, u:'tbsp', g:20 }] },
  },
  equipment:['Large skillet (12-inch)','Small pot with lid, or a rice cooker','Cutting board and knife','Two small bowls','Grater or garlic press','Instant-read thermometer (recommended)'],
  mise:['Chicken from the fridge','Rice','Cucumber, cherry tomatoes, spinach','Greek yogurt','Lemon and garlic','Olive oil, oregano, paprika, salt, pepper'],
  steps:[
    RICE_STEP,
    { title:'Season the chicken', prep:true, hands:5,
      text:'Cut {q:chicken} chicken into 1-inch pieces and pat dry. Toss with {q:oliveoil} olive oil, {q:garlic} minced garlic, {q:oregano} oregano, {q:paprika} paprika, {q:salt} salt, a pinch of pepper and {q:lemon} lemon juice.',
      warn:'Wash your hands, knife and board after handling raw chicken.' },
    { key:'chicken', title:'Sear the chicken', hands:1, passive:9, timer:9,
      text:'Heat the skillet over medium-high for 2 minutes. Add the chicken in a single layer. Leave it for 3 minutes, then stir every couple of minutes until cooked through, 8–10 minutes total.',
      warn:'Keep it at medium-high, not high. The garlic on the chicken scorches easily.', safety:CHICKEN_SAFETY },
    { title:'Make the garlic yogurt sauce', prep:true, hands:2,
      text:'Grate {q:garlicSauce} garlic into {q:yogurt} Greek yogurt. Stir in {q:lemonSauce} lemon juice and a pinch of salt. Thin with 1–2 tsp water if you want to drizzle it.' },
    { title:'Chop the vegetables', prep:true, hands:3,
      text:'Dice {q:cucumber} cucumber and halve {q:tomato} cherry tomatoes. Toss with a pinch of salt.{heat}' },
    { waitFor:'chicken', title:'Check the chicken', hands:1,
      text:'Cut open the thickest piece: no pink inside. Take the pan off the heat and let it rest for 2 minutes.', safety:CHICKEN_SAFETY },
    WARM_RICE_STEP,
    { waitAll:true, title:'Assemble', hands:2,
      text:'Put {q:spinach} spinach in the bowl and pile the hot rice on top so it wilts a little. Add the chicken, cucumber and tomatoes. Spoon the garlic yogurt sauce over.' },
    { title:'Finish', hands:1, finish:true,
      text:'Pour any pan juices over the chicken and finish with black pepper.{tierFinish}' },
  ],
  finish:'Spinach under hot rice so it softens. Chicken, cucumber and tomato on top, garlic yogurt sauce over everything, pan juices on the chicken.',
  subs:['No fresh garlic: ¼ tsp garlic powder on the chicken, a pinch in the sauce.','No spinach: romaine.','Feta is optional — it lives in Better.'],
  leftovers:{
    separate:['Chicken and rice go in one container.','Cucumber, tomato and spinach go in a separate container. They don’t reheat well.','Garlic yogurt sauce goes in its own small container.','Feta, olives and herbs go on cold, after reheating.'],
    storage:['Into the fridge within 2 hours of cooking — within 1 hour for rice if you can.','Chicken and rice: 3–4 days.','Cut cucumber and tomato: 2–3 days, with a paper towel in the container.','Garlic yogurt sauce: 3–4 days, kept cold. The garlic gets stronger each day.','Freezer: chicken and rice only, for up to 2–3 months.'],
    reheat:['Add 1 tbsp water and cover loosely.','Microwave 1½ minutes, stir, then about 1 minute more until 165°F throughout.','Stop once it’s hot, then add the cold vegetables and sauce.','Chicken came out dry? A spoon of the yogurt sauce and a squeeze of lemon fixes it.'],
    fresh:['A fresh squeeze of lemon and a pinch of salt on the cucumber.','Crumble the feta on right before eating.'],
  },
},
{
  id:'bbq', type:'dinner', name:'Smoky BBQ Beef Bowl', short:'Smoky BBQ Beef',
  flavor:'Smoked-paprika beef in sticky BBQ sauce with broccoli and corn, over rice or crispy potatoes.',
  difficulty:'Easy', protein:'beef', tags:['beef','rice or potatoes','comfort'], hasCarbChoice:true, hasSauceChoice:true,
  bowl:[['rice',0.40],['beef',0.34],['broccoli',0.16],['corn',0.10]], garnish:'bbq',
  ingredients:[
    { id:'beef', q:10, u:'oz', g:283, role:'protein', core:true, any:['beef','p_beef'], note:'raw · about 8 oz cooked' },
    { if:'rice', id:'rice', name:'Jasmine rice', q:1.5, u:'cup', g:237, role:'carb', core:true, any:['rice','p_rice','ricepouch'], note:'cooked · {dry} dry' },
    { if:'potato', id:'potatoes', q:12, u:'oz', g:340, role:'carb', core:true, note:'about 1 large, ¾-inch cubes' },
    { if:'potato', id:'oliveoil', q:1, u:'tsp', g:4.5, role:'other', note:'for crisping' },
    { id:'broccoli', q:1, u:'cup', g:90, role:'veg', core:true, note:'fresh or frozen florets' },
    { id:'corn', q:0.5, u:'cup', g:82, role:'veg', note:'frozen is fine' },
    { id:'bbq', q:2, u:'tbsp', g:34, role:'sauce', core:true, group:'Sauce' },
    { if:'sauce:smoky', id:'smokedpaprika', key:'smokyBoost', q:0.25, u:'tsp', g:0.6, role:'sauce', group:'Sauce', note:'extra, for smoky' },
    { if:'sauce:spicy', id:'hotsauce', q:0.5, u:'tsp', g:2.5, role:'sauce', group:'Sauce', note:'for spicy' },
    { id:'garlicpowder', q:0.5, u:'tsp', g:1.5, role:'other', group:'Beef seasoning' },
    { id:'onionpowder', q:0.5, u:'tsp', g:1.2, role:'other', group:'Beef seasoning' },
    { id:'smokedpaprika', q:1, u:'tsp', g:2.3, role:'other', group:'Beef seasoning', any:['smokedpaprika','paprika'], sub:'Regular paprika — less smoky.' },
    { id:'pepper', q:0.25, u:'tsp', g:0.6, role:'other', group:'Beef seasoning' },
    { id:'salt', q:0.125, u:'tsp', g:0.75, role:'other', group:'Beef seasoning', note:'BBQ sauce is salty' },
  ],
  heat:{ medium:[], hot:[] },
  heatText:'',
  tiers:{
    base:{ text:'Beef, rice or potatoes, broccoli, corn, BBQ sauce.' },
    better:{ text:'Pickles, green onion and a dusting of smoked paprika.', finish:'Add the pickles and green onion, and dust with smoked paprika.',
      add:[{ id:'pickles', q:2, u:'tbsp', g:30, note:'chopped' },{ id:'greenonion', q:1, u:'tbsp', g:6, note:'sliced' },{ id:'smokedpaprika', key:'paprikaTop', q:0.25, u:'tsp', g:0.6, note:'on top' }] },
    loaded:{ text:'Everything in Better, plus crispy onions, extra BBQ sauce and a Greek-yogurt BBQ sauce.', finish:'Pile on crispy onions and drizzle the yogurt BBQ sauce.',
      add:[{ id:'crispyonion', q:2, u:'tbsp', g:7 },{ id:'bbq', key:'bbqExtra', q:1, u:'tbsp', g:17, note:'extra, on top' },{ id:'yogurt', key:'yogurtBbq', q:2, u:'tbsp', g:30, note:'for the yogurt BBQ sauce' },{ id:'bbq', key:'bbqYogurt', q:1, u:'tbsp', g:17, note:'for the yogurt BBQ sauce' }] },
  },
  equipment:['Large skillet (12-inch)','Small pot with lid, or a rice cooker (rice)','Microwave-safe bowl and a plate to cover it','Small bowl for the seasoning','Spatula'],
  mise:['Beef from the fridge','Rice or potatoes','Broccoli and corn','BBQ sauce','Garlic powder, onion powder, smoked paprika, salt, pepper'],
  steps:[
    Object.assign({}, RICE_STEP, { if:'rice&fresh' }),
    { if:'potato', key:'potmic', title:'Par-cook the potatoes', prep:true, hands:4, passive:6, timer:6,
      text:'Cut {q:potatoes} potatoes into ¾-inch cubes — no need to peel. Put them in a microwave-safe bowl with 1 tbsp water, cover with a plate and microwave 6 minutes, until a fork goes in with slight resistance.' },
    { title:'Mix the seasoning', prep:true, hands:2,
      text:'Stir {q:garlicpowder} garlic powder, {q:onionpowder} onion powder, {q:smokedpaprika} smoked paprika, {q:pepper} black pepper and {q:salt} salt in a small bowl.' },
    { if:'potato', waitFor:'potmic', key:'potcrisp', title:'Crisp the potatoes', hands:1, passive:7, timer:7,
      text:'Drain the potatoes. Heat {q:oliveoil} oil in the skillet over medium-high. Add the potatoes in one layer with a pinch of salt and a pinch of the seasoning. Cook 6–7 minutes, turning every 2 minutes, until golden. Move them to a bowl and keep the pan hot.' },
    { waitFor:'potcrisp', key:'beef', title:'Brown the beef', hands:1, passive:7, timer:7,
      text:'Add {q:beef} beef to the hot skillet and press it flat. Brown for 2 minutes without stirring, then break it up and sprinkle in the seasoning. Cook until no pink remains, 6–8 minutes total.',
      warn:'Don’t stir right away. The browned crust is the flavor.', safety:BEEF_SAFETY },
    { key:'veg', title:'Cook the broccoli and corn', hands:1, passive:4, timer:4,
      text:'While the beef cooks: microwave {q:broccoli} broccoli and {q:corn} corn in a covered bowl with 2 tbsp water for 4 minutes. Drain.' },
    { waitFor:'beef', key:'sauce', title:'Glaze with BBQ sauce', hands:1, passive:2, timer:2,
      text:'Spoon off any pooled fat. Turn the heat to medium, stir in {q:bbq} BBQ sauce{sauceStyle}, and cook 1–2 minutes until sticky and glossy.',
      warn:'Medium heat — BBQ sauce is sugary and scorches on high.' },
    { if:'loaded', title:'Mix the yogurt BBQ sauce', prep:true, hands:1,
      text:'Stir {q:yogurtBbq} Greek yogurt with {q:bbqYogurt} BBQ sauce.' },
    Object.assign({}, WARM_RICE_STEP, { if:'rice&ready' }),
    { waitAll:true, title:'Assemble', hands:2,
      text:'{carbName} on the bottom, BBQ beef on top, broccoli and corn alongside.' },
    { title:'Finish', hands:1, finish:true,
      text:'Scrape any sauce left in the pan over the vegetables.{tierFinish}' },
  ],
  finish:'Rice or potatoes on the bottom, BBQ beef on top, broccoli and corn alongside. Scrape the pan sauce over the vegetables.',
  subs:['Potatoes instead of rice: switch Carb to Potatoes. Adds about 8 minutes.','No smoked paprika: regular paprika. A bottled hickory or mesquite BBQ sauce brings the smoke back.','Air fryer potatoes: 400°F for 15–18 minutes, shaking halfway.'],
  leftovers:{
    separate:['Beef, rice or potatoes, broccoli and corn can share one container.','Pickles, green onion, crispy onions and the yogurt BBQ sauce stay separate.','Like it saucy? Pack an extra spoon of BBQ sauce on the side and add it after heating.'],
    storage:['Into the fridge within 2 hours of cooking — within 1 hour for rice if you can.','Fridge: 3–4 days.','Freezer: up to 2–3 months. Potatoes soften in the freezer, so eat potato bowls from the fridge first and re-crisp frozen ones in a hot skillet after reheating.','Yogurt BBQ sauce: 3–4 days, kept cold.'],
    reheat:['Add 1 tbsp water and cover loosely. Microwave 1½ minutes, stir, then about 1 minute more until 165°F throughout.','Potatoes: for crisp edges, reheat them in a hot dry skillet for 3–4 minutes, or in an air fryer at 400°F for 4–5 minutes.','Add fresh BBQ sauce after heating, not before. It scorches at the edges.'],
    fresh:['Cold pickles and fresh green onion on top.','A fresh spoon of BBQ sauce and a pinch of smoked paprika.'],
  },
},

/* ---------- Desserts ---------- */
{
  id:'bread', type:'dessert', name:'Banana Chocolate Chip Protein Bread', short:'Banana Bread', want:'I want something baked',
  flavor:'A real banana bread: moist, tender, dotted with dark chocolate. The protein is a bonus, not the point.',
  difficulty:'Easy', glyph:'loaf', oven:'350°F', batchFriendly:true, bakes:true,
  yields:[
    { id:'full', label:'Full loaf', f:1, pieces:10, unit:'slice', pan:'8½ × 4½-inch loaf pan', bake:'50–60 minutes', bakeMin:55 },
    { id:'half', label:'Half loaf', f:0.5, pieces:6, unit:'muffin', pan:'6-cup muffin tin, lined or sprayed', bake:'20–25 minutes', bakeMin:22 },
    { id:'one', label:'Individual', f:0.2, pieces:2, unit:'muffin', pan:'2 muffin cups, or one 8-oz ramekin', bake:'20–24 minutes', bakeMin:22 },
  ],
  prepNotes:{ temp:'350°F, rack in the middle', lining:'Parchment with overhang on the long sides; spray the short ends', tools:['Dry measuring cups','Measuring spoons','Large bowl + medium bowl','Whisk and rubber spatula','Fork or masher','Toothpick','Cooling rack'] },
  ingredients:[
    { id:'bananas', q:3, u:'banana', g:360, core:true, note:'very ripe, heavily spotted (about 1½ cups mashed)' },
    { id:'eggs', q:2, u:'egg', g:100, core:true, note:'room temperature' },
    { id:'yogurt', q:0.5, u:'cup', g:120, core:true },
    { id:'maple', q:0.25, u:'cup', g:80, any:['maple','honey'], note:'or honey' },
    { id:'butter', q:3, u:'tbsp', g:42, any:['butter','oliveoil'], note:'melted and cooled', sub:'Neutral oil or light olive oil.' },
    { id:'vanilla', q:1, u:'tsp', g:4.2 },
    { id:'oats', name:'Oat flour', q:1.5, u:'cup', g:135, core:true, note:'or blend rolled oats until fine' },
    { id:'protein', q:0.5, u:'cup', g:45, core:true, note:'about 1½ scoops vanilla', sub:'Plant protein soaks up more liquid — add 2 tbsp milk.' },
    { id:'bakingpowder', q:2, u:'tsp', g:9, core:true },
    { id:'cinnamon', q:1, u:'tsp', g:2.6 },
    { id:'salt', q:0.25, u:'tsp', g:1.5 },
    { id:'chips', q:0.5, u:'cup', g:85, key:'chips', note:'save 1 tbsp for the top' },
  ],
  variations:[
    { id:'classic', label:'Chocolate chip', how:'The default.', mix:'Fold in the chocolate chips, saving 1 tablespoon for the top.', fill:'Scatter the saved chips on top.' },
    { id:'cinnamon', label:'Cinnamon swirl', how:'No chips. A cinnamon-sugar layer through the middle and on top.', remove:['chips'],
      add:[{ id:'sugar', q:2, u:'tbsp', g:25 },{ id:'cinnamon', key:'cinnSwirl', q:1, u:'tsp', g:2.6, note:'for the swirl' }],
      mix:'Skip the chips. Mix {q:sugar} sugar with {q:cinnSwirl} cinnamon in a small bowl.', fill:'Spread half the batter in the pan, sprinkle half the cinnamon sugar, add the rest of the batter and finish with the remaining cinnamon sugar. Drag a knife through once.' },
    { id:'blueberry', label:'Blueberry', how:'Blueberries instead of chips. Adds 5 minutes to the bake.', remove:['chips'], bakeExtra:5,
      add:[{ id:'berries', q:0.75, u:'cup', g:110, note:'blueberries, fresh or frozen (not thawed)' }],
      mix:'Toss {q:berries} blueberries with 1 tsp oat flour and fold them in gently.', fill:'Smooth the top. Add 5 minutes to the bake.' },
    { id:'pb', label:'Peanut butter', how:'Chips stay in. Warm peanut butter swirled through the top.',
      add:[{ id:'pb', q:3, u:'tbsp', g:48, note:'warmed until runny' }],
      mix:'Fold in the chocolate chips, saving 1 tablespoon for the top.', fill:'Dollop {q:pb} warm peanut butter over the batter and drag a knife through in S-shapes. Scatter the saved chips.' },
    { id:'choc', label:'Chocolate-heavy', how:'Cocoa in the batter and extra chips.',
      add:[{ id:'cocoa', q:2, u:'tbsp', g:11, note:'whisk into the dry mix' },{ id:'chips', key:'chipsExtra', q:0.25, u:'cup', g:42, note:'extra' },{ id:'milk', q:1, u:'tbsp', g:15, note:'whisk into the wet mix' }],
      mix:'Fold in all the chocolate chips, saving 1 tablespoon for the top.', fill:'Scatter the saved chips on top.',
      wet:' Whisk in {q:milk} milk too.', dry:' Add {q:cocoa} cocoa to this bowl.' },
  ],
  tiers:{
    base:{ text:'A slice, as is.' },
    better:{ text:'Toasted in a skillet with a little butter until the edges crisp.', add:[{ id:'butter', key:'butterToast', q:0.5, u:'tsp', g:2.3 }] },
    loaded:{ text:'Toasted, then spread with cream cheese and honey and a pinch of flaky salt.', add:[{ id:'butter', key:'butterToast', q:0.5, u:'tsp', g:2.3 },{ id:'creamcheese', q:1, u:'tbsp', g:15 },{ id:'honey', q:1, u:'tsp', g:7 }] },
  },
  steps:[
    { key:'oven', title:'Heat the oven and line the pan', hands:2, passive:12,
      text:'Heat the oven to 350°F with a rack in the middle. {lining}' },
    { title:'Mash the bananas', hands:3,
      text:'Mash {q:bananas} in the large bowl until mostly smooth, with a few small lumps.' },
    { title:'Whisk the wet ingredients', hands:2,
      text:'Whisk in {q:eggs}, {q:yogurt} Greek yogurt, {q:maple} maple syrup, {q:butter} melted butter and {q:vanilla} vanilla until smooth.{varWet}',
      warn:'Let the melted butter cool for 2 minutes first. Hot butter scrambles the eggs.' },
    { title:'Whisk the dry ingredients', hands:2,
      text:'In the medium bowl, whisk {q:oats} oat flour, {q:protein} protein powder, {q:bakingpowder} baking powder, {q:cinnamon} cinnamon and {q:salt} salt.{varDry} Break up any protein powder clumps.' },
    { title:'Combine — gently', hands:2,
      text:'Add the dry mix to the wet. Fold with a spatula just until no dry streaks remain.',
      warn:'Do not overmix. Stop as soon as the flour disappears — overmixing makes it tough and dry.' },
    { title:'Add the mix-ins', hands:1, text:'{mix}' },
    { key:'rest', title:'Check the batter, then rest it', hands:1, passive:5, timer:5,
      text:'It should be thick and scoopable, like thick muffin batter: it holds soft mounds and slowly settles. Too stiff to spread? Fold in 1–2 tbsp milk. Rest 5 minutes so the oat flour absorbs the liquid.' },
    { waitAll:true, title:'Fill the pan', hands:2,
      text:'Scrape the batter into the {pan} and smooth the top. {fill}' },
    { key:'bake', title:'Bake', hands:1, passive:'bake', timer:'bake',
      text:'Bake {bake}.{tent}',
      warn:'Do not overbake. Oat flour bread dries out fast — start checking at the low end of the time.' },
    { waitFor:'bake', title:'Test for doneness', hands:2,
      text:'Push a toothpick into the center. It’s done when the toothpick comes out with a few moist crumbs but no wet batter, the top springs back when pressed, and the center reads 200–205°F. Wet batter? Bake 5 more minutes and test again.' },
    { key:'cool1', title:'Cool in the pan', hands:0, passive:15, timer:15,
      text:'Leave it in the pan on a rack for 15 minutes, then lift it out by the parchment (muffins: tip them out onto the rack).' },
    { waitFor:'cool1', key:'cool2', title:'Cool before slicing', hands:0, passive:45, timer:45,
      text:'Let it cool on the rack for at least 45 minutes before cutting.',
      warn:'Let it cool before cutting. Oat flour bread is gummy while hot and sets as it cools.' },
  ],
  storeShort:'Banana bread: wrap it; fridge up to 1 week, or slice and freeze.',
  storage:{
    room:'Counter, wrapped: up to 2 days. It’s very moist, so move it to the fridge after that, or sooner in a warm kitchen.',
    fridge:'Fridge, airtight: up to 1 week.',
    freezer:'Slice it, separate the slices with parchment, and freeze in a zip bag for up to 3 months.',
    reheat:'Microwave a slice for 15–20 seconds, or toast it in a dry skillet for 1 minute per side. From frozen: 30–40 seconds.',
  },
  subs:['Honey for maple syrup, 1:1.','Oil for butter, 1:1.','No oat flour? Blend 1¾ cups rolled oats until powdery.'],
},
{
  id:'brownies', type:'dessert', name:'Fudgy Protein Brownies', short:'Brownies', want:'I want a brownie',
  flavor:'Dense, glossy and chocolate-forward. Melted dark chocolate and minimal flour keep them fudgy, not cakey.',
  difficulty:'Easy', glyph:'brownie', oven:'350°F', batchFriendly:true, bakes:true,
  yields:[
    { id:'full', label:'8×8 pan', f:1, pieces:9, unit:'brownie', pan:'8 × 8-inch metal pan', bake:'20–24 minutes', bakeMin:22 },
    { id:'half', label:'Half (loaf pan)', f:0.5, pieces:4, unit:'brownie', pan:'8½ × 4½-inch loaf pan', bake:'18–22 minutes', bakeMin:20 },
  ],
  prepNotes:{ temp:'350°F, rack in the middle', lining:'Parchment in both directions with overhang, so you can lift the slab out', tools:['Dry measuring cups','Measuring spoons','Large microwave-safe bowl','Whisk and rubber spatula','Fine sieve (optional, for cocoa)','Large knife','Cooling rack'] },
  ingredients:[
    { id:'darkchoc', q:3, u:'oz', g:85, core:true, note:'70% chocolate, chopped' },
    { id:'butter', q:2, u:'tbsp', g:28, any:['butter','oliveoil'], sub:'Neutral oil.' },
    { id:'bananas', name:'Mashed banana or applesauce', q:0.5, u:'cup', g:115, any:['bananas','applesauce'], note:'about 1 ripe banana', sub:'Unsweetened applesauce — less banana flavor, same texture.' },
    { id:'yogurt', q:0.5, u:'cup', g:120, core:true },
    { id:'eggs', q:2, u:'egg', g:100, core:true },
    { id:'maple', q:0.333, u:'cup', g:105, any:['maple','honey'], note:'or honey' },
    { id:'vanilla', q:2, u:'tsp', g:8.4 },
    { id:'cocoa', q:0.5, u:'cup', g:43, core:true },
    { id:'oats', name:'Oat flour', q:0.25, u:'cup', g:22 },
    { id:'protein', q:0.333, u:'cup', g:30, note:'1 scoop, chocolate or vanilla' },
    { id:'bakingpowder', q:0.5, u:'tsp', g:2.3 },
    { id:'salt', q:0.25, u:'tsp', g:1.5 },
  ],
  variations:[
    { id:'classic', label:'Classic', how:'The default.', mix:'', fill:'' },
    { id:'chip', label:'Chocolate chip', how:'Chips folded through.', add:[{ id:'chips', q:0.25, u:'cup', g:42 }], mix:'Fold in {q:chips} chocolate chips.', fill:'' },
    { id:'pbswirl', label:'Peanut butter swirl', how:'Warm peanut butter swirled across the top.', add:[{ id:'pb', q:3, u:'tbsp', g:48, note:'warmed until runny' }], mix:'', fill:'Dollop {q:pb} warm peanut butter over the batter and drag a knife through it in a zigzag.' },
    { id:'seasalt', label:'Sea salt', how:'Flaky salt on top before baking.', add:[{ id:'salt', key:'flaky', name:'Flaky sea salt', q:0.5, u:'tsp', g:1.5 }], mix:'', fill:'Sprinkle {q:flaky} flaky sea salt over the top.' },
    { id:'raspberry', label:'Raspberry', how:'Raspberries pressed into the top. Adds 2–3 minutes.', bakeExtra:3, add:[{ id:'berries', q:0.5, u:'cup', g:62, note:'raspberries' }], mix:'', fill:'Press {q:berries} raspberries lightly into the top. Add 2–3 minutes to the bake.' },
  ],
  tiers:{
    base:{ text:'A square, cold or room temperature.' },
    better:{ text:'Warmed 10 seconds, with a pinch of flaky salt.', add:[{ id:'salt', key:'flakyTop', q:0.03, u:'tsp', g:0.2, note:'pinch' }] },
    loaded:{ text:'Warm, with Greek yogurt whipped with maple and a peanut butter drizzle.', add:[{ id:'yogurt', key:'yogurtTop', q:0.25, u:'cup', g:60 },{ id:'maple', key:'mapleTop', q:1, u:'tsp', g:7 },{ id:'pb', key:'pbTop', q:1, u:'tsp', g:5 }] },
  },
  steps:[
    { key:'oven', title:'Heat the oven and line the pan', hands:2, passive:12,
      text:'Heat the oven to 350°F with a rack in the middle. {lining}' },
    { title:'Melt the chocolate', hands:3,
      text:'Microwave {q:darkchoc} chopped chocolate and {q:butter} butter in the large bowl in 30-second bursts, stirring between each, until smooth — about 1 minute total.',
      warn:'Stop while a few pieces remain and stir them in. Overheated chocolate turns grainy.' },
    { title:'Whisk in the wet ingredients', hands:3,
      text:'Whisk in {q:bananas} mashed banana, {q:yogurt} Greek yogurt, {q:maple} maple syrup and {q:vanilla} vanilla. Add {q:eggs} and whisk hard for 30 seconds, until glossy.',
      tip:'If the chocolate stiffens when the cold yogurt goes in, microwave 10 seconds and whisk again.' },
    { title:'Add the dry ingredients', hands:2,
      text:'Sift or whisk in {q:cocoa} cocoa, {q:oats} oat flour, {q:protein} protein powder, {q:bakingpowder} baking powder and {q:salt} salt. Fold just until combined. {mix}',
      warn:'Do not overmix. Overworked protein batter bakes up cakey.' },
    { title:'Check the batter', hands:1,
      text:'It should be thick and glossy, like soft frosting: it spreads, but holds a ridge. Too stiff to spread? Stir in 1 tbsp milk.' },
    { waitAll:true, title:'Fill the pan', hands:2,
      text:'Spread the batter into the {pan} and smooth the top. {fill}' },
    { key:'bake', title:'Bake', hands:1, passive:'bake', timer:'bake',
      text:'Bake {bake}.',
      warn:'Do not overbake. Pull them early — they keep setting as they cool.' },
    { waitFor:'bake', title:'Check doneness', hands:2,
      text:'They’re done when the edges are set and just pulling away, the center looks matte rather than shiny-wet, and a toothpick 1 inch from the center comes out with moist, fudgy crumbs. Wet batter on the toothpick? 2–3 more minutes.' },
    { key:'cool', title:'Cool completely', hands:0, passive:60, timer:60,
      text:'Cool in the pan on a rack for 1 hour.',
      warn:'Let them cool before cutting. Warm protein brownies fall apart; they turn fudgy as they cool.' },
    { waitFor:'cool', title:'Chill and cut', hands:3, passive:30, timer:30,
      text:'For clean squares, refrigerate for 30 minutes. Lift the slab out by the parchment and cut into {pieces} pieces with a large knife, wiping the blade with a hot damp towel between cuts.' },
  ],
  storeShort:'Brownies: cut, then fridge up to 5 days or wrap and freeze.',
  storage:{
    room:'Counter, covered: 1 day. With banana and yogurt in them, they keep best cold.',
    fridge:'Fridge, airtight: up to 5 days. Cold, they’re dense and extra fudgy.',
    freezer:'Wrap squares individually and freeze for up to 3 months.',
    reheat:'Eat cold, or microwave 10–15 seconds. From frozen: 30 minutes on the counter, or 25 seconds in the microwave.',
  },
  subs:['Applesauce for banana, 1:1.','Honey for maple syrup, 1:1.','Chocolate protein powder deepens the chocolate flavor.'],
},
{
  id:'donuts', type:'dessert', name:'Homemade Protein Donuts', short:'Protein Donuts', want:'I want a donut',
  flavor:'Soft, cinnamon-scented baked donuts with a glaze you pick. Easier than they look once you know the batter.',
  difficulty:'Moderate', glyph:'donut', oven:'350°F', bakes:true,
  yields:[
    { id:'six', label:'6 donuts', f:1, pieces:6, unit:'donut', pan:'6-cavity donut pan', bake:'11–14 minutes', bakeMin:12 },
    { id:'twelve', label:'12 donuts', f:2, pieces:12, unit:'donut', pan:'two 6-cavity donut pans, or one pan baked twice', bake:'11–14 minutes per pan', bakeMin:12 },
  ],
  prepNotes:{ temp:'350°F, rack in the middle', lining:'Brush or spray every cavity well, including the center posts', tools:['Donut pan','Dry measuring cups','Measuring spoons','Two bowls, whisk, spatula','Zip-top bag for piping','Thin spatula or butter knife','Cooling rack'] },
  ingredients:[
    { id:'oats', name:'Oat flour', q:1, u:'cup', g:90, core:true },
    { id:'protein', q:0.333, u:'cup', g:35, core:true, note:'vanilla, about 1 heaping scoop' },
    { id:'bakingpowder', q:1.5, u:'tsp', g:7, core:true },
    { id:'cinnamon', q:1, u:'tsp', g:2.6 },
    { id:'salt', q:0.125, u:'tsp', g:0.75 },
    { id:'eggs', q:1, u:'egg', g:50, core:true },
    { id:'yogurt', q:0.333, u:'cup', g:80, core:true },
    { id:'milk', q:0.25, u:'cup', g:60, core:true, note:'plus 1–2 tbsp if needed' },
    { id:'maple', q:3, u:'tbsp', g:60, any:['maple','honey'], note:'or honey' },
    { id:'butter', q:1, u:'tbsp', g:14, any:['butter','oliveoil'], note:'melted, plus more for the pan' },
    { id:'vanilla', q:1, u:'tsp', g:4.2 },
  ],
  glazes:[
    { id:'none', label:'No glaze', ing:[] },
    { id:'chocolate', label:'Chocolate', ing:[{ id:'powdered', q:0.5, u:'cup', g:60 },{ id:'cocoa', q:2, u:'tbsp', g:11 },{ id:'milk', key:'glazeMilk', q:2, u:'tbsp', g:30 }],
      make:'Whisk {q:powdered} powdered sugar, {q:cocoa} cocoa and {q:glazeMilk} milk until smooth and thick enough to coat a spoon. Too thick? Add milk ½ tsp at a time.',
      apply:'Dip the top of each donut into the glaze, twist and lift. Let them set on the rack for 10 minutes.' },
    { id:'vanilla', label:'Vanilla', ing:[{ id:'powdered', q:0.667, u:'cup', g:80 },{ id:'milk', key:'glazeMilk', q:1.5, u:'tbsp', g:22 },{ id:'vanilla', key:'glazeVanilla', q:0.5, u:'tsp', g:2.1 }],
      make:'Whisk {q:powdered} powdered sugar, {q:glazeMilk} milk and {q:glazeVanilla} vanilla until smooth. It should fall off the whisk in a thick ribbon.',
      apply:'Dip the top of each donut into the glaze, twist and lift. Let them set on the rack for 10 minutes.' },
    { id:'cinnamon', label:'Cinnamon sugar', warm:true, ing:[{ id:'sugar', q:3, u:'tbsp', g:37 },{ id:'cinnamon', key:'glazeCinn', q:1.5, u:'tsp', g:4 },{ id:'butter', key:'glazeButter', q:1, u:'tbsp', g:14, note:'melted, for brushing' }],
      make:'Mix {q:sugar} sugar and {q:glazeCinn} cinnamon in a shallow bowl. Melt {q:glazeButter} butter.',
      apply:'While the donuts are still slightly warm, brush the tops with melted butter and press them into the cinnamon sugar.' },
    { id:'chocpb', label:'Chocolate peanut butter', cold:true, ing:[{ id:'pb', q:3, u:'tbsp', g:48 },{ id:'cocoa', q:1.5, u:'tbsp', g:8 },{ id:'yogurt', key:'glazeYogurt', q:3, u:'tbsp', g:45 },{ id:'maple', key:'glazeMaple', q:1, u:'tbsp', g:20, note:'to taste' }],
      make:'Stir {q:pb} peanut butter, {q:cocoa} cocoa, {q:glazeYogurt} Greek yogurt and {q:glazeMaple} maple syrup until smooth.',
      apply:'Spread a spoonful over each donut. This glaze contains yogurt, so keep these donuts in the fridge.' },
  ],
  tiers:{
    base:{ text:'A donut with your glaze.' },
    better:{ text:'Chopped dark chocolate pressed into the wet glaze.', add:[{ id:'chips', key:'chipsTop', q:1, u:'tsp', g:4, note:'chopped' }] },
    loaded:{ text:'Chocolate on the glaze, a peanut butter drizzle and a pinch of flaky salt.', add:[{ id:'chips', key:'chipsTop', q:1, u:'tsp', g:4 },{ id:'pb', key:'pbTop', q:1, u:'tsp', g:5 }] },
  },
  steps:[
    { key:'oven', title:'Heat the oven and grease the pan', hands:2, passive:12,
      text:'Heat the oven to 350°F. {lining}' },
    { title:'Whisk the dry ingredients', hands:2,
      text:'In one bowl, whisk {q:oats} oat flour, {q:protein} protein powder, {q:bakingpowder} baking powder, {q:cinnamon} cinnamon and {q:salt} salt.' },
    { title:'Whisk the wet ingredients', hands:2,
      text:'In another bowl, whisk {q:eggs}, {q:yogurt} Greek yogurt, {q:milk} milk, {q:maple} maple syrup, {q:butter} melted butter and {q:vanilla} vanilla.' },
    { title:'Combine', hands:2,
      text:'Pour the wet into the dry and stir with a spatula just until smooth.',
      warn:'Do not overmix. A few tiny lumps are fine.' },
    { key:'rest', title:'Check the batter', hands:1, passive:5, timer:5,
      text:'It should be thick but pipeable, like thick pancake batter that falls off the spoon in a slow ribbon. Too thick to pipe? Add milk 1 tbsp at a time. Rest 5 minutes — it thickens slightly.' },
    { waitAll:true, title:'Fill the pan', hands:4,
      text:'Spoon the batter into a zip-top bag, snip off a ½-inch corner and pipe a ring into each cavity until it’s about ¾ full. Tap the pan on the counter twice to level.',
      warn:'Fill only ¾ full. Overfilled donuts rise over the center post and lose their hole.' },
    { key:'bake', title:'Bake', hands:1, passive:'bake', timer:'bake',
      text:'Bake {bake}, until the tops spring back when pressed and a toothpick comes out clean.',
      warn:'Do not overbake. They go from tender to dry in about 2 minutes.' },
    { waitFor:'bake', key:'cool1', title:'Cool in the pan', hands:0, passive:5, timer:5,
      text:'Leave them in the pan for 5 minutes. They firm up enough to come out cleanly.' },
    { if:'warmglaze', title:'Make the cinnamon sugar', hands:2, text:'{glazeMake}' },
    { waitFor:'cool1', title:'Remove from the pan', hands:2,
      text:'Run a thin spatula or butter knife around the outer edge and the center post of each donut. Turn the pan over the rack and tap; ease out any stubborn ones with a gentle twist.' },
    { if:'warmglaze', title:'Coat while warm', hands:3, text:'{glazeApply}' },
    { if:'coldglaze', key:'cool2', title:'Cool before glazing', hands:0, passive:15, timer:15,
      text:'Cool on the rack for 15 minutes.',
      warn:'Glaze on warm donuts melts and slides off.' },
    { if:'unglazed', title:'Cool on the rack', hands:0, passive:15, timer:15,
      text:'Cool on the rack for 15 minutes. Eat one warm if you like.' },
    { if:'coldglaze', title:'Make the glaze', hands:3, text:'{glazeMake}' },
    { if:'coldglaze', waitFor:'cool2', title:'Glaze', hands:3, text:'{glazeApply}' },
  ],
  storeShort:'Donuts: airtight, 1 day on the counter or 3 in the fridge (chocolate peanut butter glaze always in the fridge).',
  storage:{
    room:'Unglazed, or with chocolate, vanilla or cinnamon-sugar glaze: 1 day at room temperature, loosely covered.',
    fridge:'Fridge, airtight: 3 days. Chocolate peanut butter glaze contains yogurt, so those always go in the fridge.',
    freezer:'Freeze unglazed donuts for up to 2 months. Thaw 30 minutes at room temperature, then glaze.',
    reheat:'Warm an unglazed donut for 8–10 seconds in the microwave, then glaze.',
  },
  subs:['Honey for maple syrup.','No donut pan: a muffin tin works (bake 16–18 minutes). They’ll be muffins, not donuts.','Pan sticking? Grease with butter rather than spray, and get the center posts.'],
},
{
  id:'icecream', type:'dessert', name:'Homemade Protein Ice Cream', short:'Protein Ice Cream', want:'I want ice cream',
  flavor:'Thick soft-serve from frozen banana, Greek yogurt and a little protein. No ice cream machine.',
  difficulty:'Easy', glyph:'scoop', oven:null, bakes:false,
  yields:[
    { id:'one', label:'1 bowl', f:1, pieces:1, unit:'bowl' },
    { id:'two', label:'2 bowls', f:2, pieces:2, unit:'bowl' },
    { id:'four', label:'4 bowls', f:4, pieces:4, unit:'bowl' },
  ],
  prepNotes:{ temp:'No oven', lining:'Loaf pan or shallow container if you want it scoopable', tools:['High-powered blender or food processor','Measuring spoons','Tamper or spatula','Freezer'] },
  ahead:'Freeze the bananas first: peel ripe bananas, slice into ½-inch coins, and freeze flat on parchment for at least 6 hours. Whole frozen bananas are hard on blenders.',
  ingredients:[
    { id:'bananas', q:1, u:'banana', g:120, core:true, note:'large, sliced and frozen' },
    { id:'yogurt', q:0.333, u:'cup', g:80, core:true },
    { id:'milk', q:2, u:'tbsp', g:30, core:true, note:'exactly — add more only if the blender stalls' },
    { id:'protein', q:0.5, u:'scoop', g:15, note:'no more than ½ scoop per banana' },
    { id:'vanilla', q:0.5, u:'tsp', g:2.1 },
    { id:'salt', q:0.03, u:'tsp', g:0.2, note:'a pinch' },
  ],
  variations:[
    { id:'vanilla', label:'Vanilla', how:'The base: banana, yogurt, vanilla.', blend:'' },
    { id:'chocolate', label:'Chocolate', how:'Cocoa and a little maple.', add:[{ id:'cocoa', q:1, u:'tbsp', g:5.4 },{ id:'maple', q:1, u:'tsp', g:7 }], blend:' Add {q:cocoa} cocoa and {q:maple} maple syrup.' },
    { id:'pb', label:'Peanut butter', how:'A spoon of peanut butter blended in.', add:[{ id:'pb', q:1, u:'tbsp', g:16 }], blend:' Add {q:pb} peanut butter.' },
    { id:'strawberry', label:'Strawberry', how:'Frozen strawberries. You may need 1 extra tbsp milk.', add:[{ id:'berries', q:0.5, u:'cup', g:75, note:'frozen strawberries' }], blend:' Add {q:berries} frozen strawberries on top with the banana.' },
    { id:'chocbanana', label:'Chocolate banana', how:'Cocoa blended in, chips folded through.', add:[{ id:'cocoa', q:1, u:'tbsp', g:5.4 },{ id:'chips', q:1, u:'tbsp', g:11, note:'chopped, folded in at the end' }], blend:' Add {q:cocoa} cocoa. Fold in {q:chips} chopped chocolate chips after blending.' },
    { id:'cookies', label:'Cookies & cream style', how:'Crushed graham crackers folded through a vanilla base.', add:[{ id:'graham', q:1, u:'sheet', g:14, note:'crushed, folded in at the end' }], blend:' After blending, fold in {q:graham} crushed graham cracker (chocolate grahams if you have them).' },
  ],
  tiers:{
    base:{ text:'A bowl as blended.' },
    better:{ text:'Crushed graham cracker on top and a pinch of flaky salt.', add:[{ id:'graham', key:'grahamTop', q:0.5, u:'sheet', g:7 }] },
    loaded:{ text:'A peanut butter drizzle and dark chocolate chips on top.', add:[{ id:'pb', key:'pbTop', q:1, u:'tbsp', g:16 },{ id:'chips', key:'chipsTop', q:1, u:'tbsp', g:11 }] },
  },
  steps:[
    { title:'Load the blender — liquid first', hands:2,
      text:'Add {q:milk} milk first (liquid at the bottom helps the blades), then {q:yogurt} Greek yogurt, {q:protein} protein powder, {q:vanilla} vanilla and a pinch of salt.{blend} Put the frozen banana coins ({q:bananas}) on top.',
      warn:'Exact liquid: 2 tbsp milk per banana. That’s the line between soft-serve and a smoothie.' },
    { title:'Blend', hands:3,
      text:'Pulse 8–10 times to break up the banana, then blend on low, stopping to scrape down and push the mixture into the blades. It takes 1–2 minutes and looks crumbly before it suddenly turns smooth.',
      warn:'Add milk only 1 tbsp at a time, and only if the blender truly stalls. More than ¼ cup per bowl turns it into a smoothie.' },
    { title:'Check the texture', hands:1,
      text:'You want thick soft-serve that holds a peak on the spoon. Too thin? Blend in a few more frozen banana coins. Too thick to move? 1 tbsp milk.' },
    { title:'Serve now, or firm it up', hands:1,
      text:'Eat it now as soft-serve, or spread it in a loaf pan, cover and freeze for 30–45 minutes for a scoopable texture.' },
    { title:'Store the rest', hands:1,
      text:'Freeze extra in a shallow container with plastic wrap pressed on the surface. It freezes hard: let it sit 10–15 minutes before scooping, or break it into chunks and re-blend with 1–2 tbsp milk.' },
  ],
  trouble:[
    ['Watery, like a smoothie','Too much liquid, or the bananas weren’t fully frozen. Blend in more frozen banana, or freeze 30 minutes and re-blend.'],
    ['A rock-hard brick after freezing','Normal for a low-sugar base. Soften 10–15 minutes, or re-blend chunks with 1–2 tbsp milk. Stirring in 1 tsp maple syrup per bowl before freezing keeps it more scoopable.'],
    ['Icy crystals','Freeze it in a shallow container with plastic wrap pressed right on the surface.'],
    ['Gummy or chalky','Too much protein powder. Keep it to ½ scoop per banana.'],
    ['The blender stalls','Let the bananas sit 3–5 minutes, cut smaller coins, and use pulse.'],
  ],
  storeShort:'Ice cream: keep the banana coins frozen and blend a bowl when you want one.',
  storage:{
    room:'Serve right away. Once it has melted or sat out for more than 2 hours, discard it rather than refreezing.',
    fridge:'Not in the fridge — it melts.',
    freezer:'Up to 2 weeks for the best texture, in a shallow covered container.',
    reheat:'To soften: 10–15 minutes on the counter, or 10 seconds in the microwave.',
  },
  subs:['Any milk works, including oat or almond.','No protein powder: leave it out and use ½ cup Greek yogurt.','Food processor instead of a blender: works well, just scrape more often.'],
},
];
const RECIPE = Object.fromEntries(RECIPES.map(r => [r.id, r]));
const DINNERS = RECIPES.filter(r => r.type === 'dinner');
const DESSERTS = RECIPES.filter(r => r.type === 'dessert');

/* ---------- 5-minute mode: assemble from what's already cooked ---------- */
const QUICK = [
  { id:'q-korean', name:'Korean beef, reheated', time:5, like:'korean',
    ing:[
      { id:'p_beef', name:'Cooked ground beef', q:1.5, u:'cup', g:227, core:true, note:'about 8 oz' },
      { id:'p_rice', name:'Cooked rice or a rice pouch', q:1.5, u:'cup', g:237, core:true, any:['p_rice','ricepouch'] },
      { id:'soy', q:1, u:'tbsp', g:16, core:true },
      { id:'honey', q:1, u:'tsp', g:7, any:['honey','maple'] },
      { id:'broccoli', q:1, u:'cup', g:90, opt:true, note:'frozen' },
      { id:'greenonion', q:1, u:'tbsp', g:6, opt:true },
    ],
    steps:['Microwave the rice: a pouch for 90 seconds, or cooked rice with 1 tbsp water, covered, 1½–2 minutes.','Stir the soy sauce and honey into the beef. Cover and microwave 1½ minutes, stir, then 30–60 seconds more until steaming.','Frozen broccoli, if you have it: microwave covered with a splash of water for 3–4 minutes.','Beef over rice. Green onion on top.'] },
  { id:'q-mexican', name:'Chicken, rice, salsa and yogurt', time:5, like:'mexican',
    ing:[
      { id:'p_chicken', name:'Cooked chicken', q:1.5, u:'cup', g:227, core:true, note:'about 8 oz' },
      { id:'p_rice', name:'Cooked rice or a rice pouch', q:1.5, u:'cup', g:237, core:true, any:['p_rice','ricepouch'] },
      { id:'salsa', q:3, u:'tbsp', g:48, core:true },
      { id:'yogurt', q:3, u:'tbsp', g:45, core:true },
      { id:'blackbeans', q:0.333, u:'cup', g:57, opt:true },
      { id:'lime', q:1, u:'wedge', g:5, opt:true, any:['lime','lemon'] },
    ],
    steps:['Put chicken and rice (and beans, if you have them) in a bowl with 1 tbsp water. Cover and microwave 2 minutes, stir, then 1 minute more until steaming (165°F).','Stir the yogurt with 1 tbsp salsa and a squeeze of lime.','Top with the rest of the salsa and the sauce.'] },
  { id:'q-bbq', name:'BBQ beef bowl, shortcut', time:6, like:'bbq',
    ing:[
      { id:'p_beef', name:'Cooked ground beef', q:1.5, u:'cup', g:227, core:true, note:'about 8 oz' },
      { id:'p_rice', name:'Cooked rice or a rice pouch', q:1.5, u:'cup', g:237, core:true, any:['p_rice','ricepouch'] },
      { id:'bbq', q:2, u:'tbsp', g:34, core:true },
      { id:'corn', q:0.5, u:'cup', g:82, opt:true },
      { id:'broccoli', q:1, u:'cup', g:90, opt:true },
      { id:'pickles', q:2, u:'tbsp', g:30, opt:true },
    ],
    steps:['Microwave the corn and broccoli, covered with a splash of water, for 3–4 minutes.','Stir the BBQ sauce into the beef. Cover and microwave 1½ minutes, stir, then 30–60 seconds until steaming.','Heat the rice (pouch 90 seconds). Beef over rice, vegetables alongside, pickles on top.'] },
  { id:'q-med', name:'Mediterranean plate, shortcut', time:6, like:'med',
    ing:[
      { id:'p_chicken', name:'Cooked chicken', q:1.5, u:'cup', g:227, core:true },
      { id:'p_rice', name:'Cooked rice or a rice pouch', q:1.5, u:'cup', g:237, core:true, any:['p_rice','ricepouch'] },
      { id:'yogurt', q:0.25, u:'cup', g:60, core:true },
      { id:'lemon', q:1, u:'tsp', g:5, any:['lemon','lime'] },
      { id:'garlicpowder', name:'Garlic', q:0.125, u:'tsp', g:0.4, any:['garlicpowder','garlic'] },
      { id:'cucumber', q:0.5, u:'cup', g:70, opt:true },
      { id:'tomato', q:0.5, u:'cup', g:90, opt:true },
    ],
    steps:['Stir the yogurt with lemon, a pinch of garlic and a pinch of salt.','Microwave chicken and rice with 1 tbsp water, covered, 2 minutes; stir; 1 minute more until steaming.','Top with whatever fresh vegetables you have and the sauce.'] },
  { id:'q-egg', name:'Egg and rice bowl', time:7,
    ing:[
      { id:'eggs', q:3, u:'egg', g:150, core:true },
      { id:'ricepouch', name:'Rice pouch or cooked rice', q:1.5, u:'cup', g:237, core:true, any:['ricepouch','p_rice'] },
      { id:'soy', q:2, u:'tsp', g:11, core:true },
      { id:'sesameoil', q:0.5, u:'tsp', g:2.3, opt:true },
      { id:'greenonion', q:1, u:'tbsp', g:6, opt:true },
      { id:'broccoli', q:1, u:'cup', g:90, opt:true },
    ],
    steps:['Heat the rice.','Whisk 3 eggs with a pinch of salt. Cook in a nonstick pan over medium-low, stirring slowly, 2–3 minutes until softly set with no liquid left.','Eggs over rice, then soy sauce, sesame oil and green onion.'] },
  { id:'q-yogurt', name:'Greek yogurt bowl', time:2, note:'Lighter than dinner, still about 30 g protein.',
    ing:[
      { id:'yogurt', q:1, u:'cup', g:240, core:true },
      { id:'bananas', q:1, u:'banana', g:118, core:true },
      { id:'pb', q:1, u:'tbsp', g:16 },
      { id:'berries', q:0.5, u:'cup', g:75, opt:true },
      { id:'honey', q:1, u:'tsp', g:7, opt:true, any:['honey','maple'] },
    ],
    steps:['Yogurt in a bowl, banana sliced on top, peanut butter and berries, a drizzle of honey.'] },
];
